const childInfo = [
    // 화속성 1~42
    {
      'id': 1,
      'image': process.env.PUBLIC_URL + 'img/Brigitte.jpg',
      'name': '브리지드',
      'normalSkill': '일반스킬',
      'amplifiSkill': '증폭스킬',
      'normalDungeon': 'A',
      'amplifiDungeon': 'S',
      'normalRumble': 'A',
      'amplifiRumble': 'S',
      'normalDuel': 'A',
      'amplifiDuel':'S',
      'normalRaid': 'B',
      'amplifiRaid': 'A',
      'normalWorldBoss': 'B',
      'amplifiWorldBoss': 'A',
      'normalTotal': 'A',
      'amplifiTotal': 'S',
    },
    {
      'id': 2,
      'image': process.env.PUBLIC_URL + 'img/Venerable Blade Tiamat.jpg',
      'name': '고검 티아마트',
      'normalSkill': '일반스킬',
      'amplifiSkill': '증폭스킬',
      'normalDungeon': 'A',
      'amplifiDungeon': 'A',
      'normalRumble': 'C',
      'amplifiRumble': 'C',
      'normalDuel': 'C',
      'amplifiDuel':'C',
      'normalRaid': 'S',
      'amplifiRaid': 'S',
      'normalWorldBoss': 'B',
      'amplifiWorldBoss': 'B',
      'normalTotal': 'A',
      'amplifiTotal': 'A',
    },
    {
        'id': 3,
        'image': process.env.PUBLIC_URL + 'img/Morgan.jpg',
        'name': '모건',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 4,
        'image': process.env.PUBLIC_URL + 'img/Sweet Leda.jpg',
        'name': '러블리 레다',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 5,
        'image': process.env.PUBLIC_URL + 'img/Berry Davi.jpg',
        'name': '베리드 다비',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A+',
        'amplifiRaid': 'A+',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 6,
        'image': process.env.PUBLIC_URL + 'img/Fashination Bathori.jpg',
        'name': '매혹 바토리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 7,
        'image': process.env.PUBLIC_URL + 'img/Cain.jpg',
        'name': '카인',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 8,
        'image': process.env.PUBLIC_URL + 'img/Tirfing.jpg',
        'name': '티르빙',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 9,
        'image': process.env.PUBLIC_URL + 'img/Medb.jpg',
        'name': '메브',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 10,
        'image': process.env.PUBLIC_URL + 'img/Saladin.jpg',
        'name': '살라딘',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 11,
        'image': process.env.PUBLIC_URL + 'img/Ziva.jpg',
        'name': '지바',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 12,
        'image': process.env.PUBLIC_URL + 'img/Kouka.jpg',
        'name': '코우카',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 13,
        'image': process.env.PUBLIC_URL + 'img/Hestia.jpg',
        'name': '헤스티아',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'C',
        'amplifiTotal': 'A',
      },
      {
        'id': 14,
        'image': process.env.PUBLIC_URL + 'img/Mezmerizing Nine Tail Fox.jpg',
        'name': '구미호',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'S',
        'normalDuel': 'A',
        'amplifiDuel':'A+',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'S',
      },
      {
        'id': 15,
        'image': process.env.PUBLIC_URL + 'img/Limos.jpg',
        'name': '리모스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'S',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'S',
      },
      {
        'id': 16,
        'image': process.env.PUBLIC_URL + 'img/Ailill.jpg',
        'name': '알릴',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 17,
        'image': process.env.PUBLIC_URL + 'img/Leifang.jpg',
        'name': '레이팡',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 18,
        'image': process.env.PUBLIC_URL + 'img/School Life Eve.jpg',
        'name': '스쿨라이프 이브',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B+',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 19,
        'image': process.env.PUBLIC_URL + 'img/Demeter.jpg',
        'name': '드미테르',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 20,
        'image': process.env.PUBLIC_URL + 'img/Nine.jpg',
        'name': '나인',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 21,
        'image': process.env.PUBLIC_URL + 'img/Kalaratri.jpg',
        'name': '카라라트리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 22,
        'image': process.env.PUBLIC_URL + 'img/Jupiter.jpg',
        'name': '주피터',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B+',
        'amplifiDungeon': 'B+',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'A+',
      },
      {
        'id': 23,
        'image': process.env.PUBLIC_URL + 'img/Tragic Rusalka.jpg',
        'name': '비극의 루살카',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 24,
        'image': process.env.PUBLIC_URL + 'img/Fennec.jpg',
        'name': '사막여우',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 25,
        'image': process.env.PUBLIC_URL + 'img/Verdel.jpg',
        'name': '베르들레',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 26,
        'image': process.env.PUBLIC_URL + 'img/Redqueen.jpg',
        'name': '레드퀸',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 27,
        'image': process.env.PUBLIC_URL + 'img/Failnaught.jpg',
        'name': '페일노트',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 28,
        'image': process.env.PUBLIC_URL + 'img/Myra.jpg',
        'name': '마이라',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 29,
        'image': process.env.PUBLIC_URL + 'img/Christmas Leda.jpg',
        'name': '크리스마스 레다',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 30,
        'image': process.env.PUBLIC_URL + 'img/Halloween Star Medb.jpg',
        'name': '할로윈스타 메브',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 31,
        'image': process.env.PUBLIC_URL + 'img/Hermes.jpg',
        'name': '에르메스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'C',
        'amplifiTotal': 'C',
      },
      {
        'id': 32,
        'image': process.env.PUBLIC_URL + 'img/Dinashi.jpg',
        'name': '디나시',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 33,
        'image': process.env.PUBLIC_URL + 'img/Mahui Hyenang.jpg',
        'name': '마희 혜낭',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 34,
        'image': process.env.PUBLIC_URL + 'img/Skin Diver Mona.jpg',
        'name': '스킨다이버 모나',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 35,
        'image': process.env.PUBLIC_URL + 'img/Argus.jpg',
        'name': '아르고스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'B+',
        'amplifiDuel':'B+',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 36,
        'image': process.env.PUBLIC_URL + 'img/Catherine.jpg',
        'name': '바람둥이 캐서린',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'B+',
        'amplifiDuel':'B+',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 37,
        'image': process.env.PUBLIC_URL + 'img/Hades.jpg',
        'name': '하데스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 38,
        'image': process.env.PUBLIC_URL + 'img/Cacus.jpg',
        'name': '카쿠스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'A',
        'amplifiDuel':'S',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 39,
        'image': process.env.PUBLIC_URL + 'img/Revelator Dana.jpg',
        'name': '계시자 다나',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 40,
        'image': process.env.PUBLIC_URL + 'img/Honoka.jpg',
        'name': '호노카',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 41,
        'image': process.env.PUBLIC_URL + 'img/Aurora.jpg',
        'name': '아우로라',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 42,
        'image': process.env.PUBLIC_URL + 'img/Laufey.jpg',
        'name': '라우페이',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },

      //수속성 43~90
      {
        'id': 43,
        'image': process.env.PUBLIC_URL + 'img/Kasumi.jpg',
        'name': '카스미',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 44,
        'image': process.env.PUBLIC_URL + 'img/Lurking Mafdet.jpg',
        'name': '잠복수사 마프데트',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 45,
        'image': process.env.PUBLIC_URL + 'img/Kaka.jpg',
        'name': '카카',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 46,
        'image': process.env.PUBLIC_URL + 'img/Dark Side Liza.jpg',
        'name': '다크사이더 리자',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'S',
        'normalDuel': 'B',
        'amplifiDuel':'A',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A+',
      },
      {
        'id': 47,
        'image': process.env.PUBLIC_URL + 'img/Noel.jpg',
        'name': '노엘',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 48,
        'image': process.env.PUBLIC_URL + 'img/Nirrti.jpg',
        'name': '멸제 니르티',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'S',
      },
      {
        'id': 49,
        'image': process.env.PUBLIC_URL + 'img/Procel.jpg',
        'name': '프로켈',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 50,
        'image': process.env.PUBLIC_URL + 'img/Chun Li.jpg',
        'name': '춘리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 51,
        'image': process.env.PUBLIC_URL + 'img/Saturn.jpg',
        'name': '새턴',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'S',
        'amplifiDungeon': 'S',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 52,
        'image': process.env.PUBLIC_URL + 'img/Expert Deino.jpg',
        'name': '데이노',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A+',
        'amplifiRaid': 'A+',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 53,
        'image': process.env.PUBLIC_URL + 'img/Serket.jpg',
        'name': '세르케트',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'S',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 54,
        'image': process.env.PUBLIC_URL + 'img/Bari.jpg',
        'name': '바리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 55,
        'image': process.env.PUBLIC_URL + 'img/Eve.jpg',
        'name': '이브',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 56,
        'image': process.env.PUBLIC_URL + 'img/Salome.jpg',
        'name': '살로메',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 57,
        'image': process.env.PUBLIC_URL + 'img/Thanatos.jpg',
        'name': '타나토스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'C',
        'amplifiTotal': 'B',
      },
      {
        'id': 58,
        'image': process.env.PUBLIC_URL + 'img/Harpy.jpg',
        'name': '하피',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 59,
        'image': process.env.PUBLIC_URL + 'img/Santaclaus.jpg',
        'name': '산타',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 60,
        'image': process.env.PUBLIC_URL + 'img/Scion Babel.jpg',
        'name': '바벨',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'A',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 61,
        'image': process.env.PUBLIC_URL + 'img/Mercury.jpg',
        'name': '머큐리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 62,
        'image': process.env.PUBLIC_URL + 'img/Billy.jpg',
        'name': '빌리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 63,
        'image': process.env.PUBLIC_URL + 'img/Myrina.jpg',
        'name': '미리나',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 64,
        'image': process.env.PUBLIC_URL + 'img/Isolde.jpg',
        'name': '이졸데',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 65,
        'image': process.env.PUBLIC_URL + 'img/Wola.jpg',
        'name': '월아',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 66,
        'image': process.env.PUBLIC_URL + 'img/Methuselah.jpg',
        'name': '므두셀라',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'C',
        'amplifiTotal': 'C',
      },
      {
        'id': 67,
        'image': process.env.PUBLIC_URL + 'img/Sang Ah.jpg',
        'name': '상아',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'S',
        'amplifiDungeon': 'S',
        'normalRumble': 'S',
        'amplifiRumble': 'S',
        'normalDuel': 'S',
        'amplifiDuel':'S',
        'normalRaid': 'A+',
        'amplifiRaid': 'A+',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 68,
        'image': process.env.PUBLIC_URL + 'img/Thetis.jpg',
        'name': '테티스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'S',
        'amplifiDuel':'S',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 69,
        'image': process.env.PUBLIC_URL + 'img/Anemone.jpg',
        'name': '아네모네',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A+',
        'amplifiRaid': 'A+',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 70,
        'image': process.env.PUBLIC_URL + 'img/Labyrinth Thisbe.jpg',
        'name': '티스베',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 71,
        'image': process.env.PUBLIC_URL + 'img/P.Snow Miku.jpg',
        'name': 'SNOW MIKU',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 72,
        'image': process.env.PUBLIC_URL + 'img/Marine Suit Davi.jpg',
        'name': '마린슈트 다비',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 73,
        'image': process.env.PUBLIC_URL + 'img/Hatsune Miku.jpg',
        'name': '하츠네미쿠',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'A',
      },
      {
        'id': 74,
        'image': process.env.PUBLIC_URL + 'img/Leo.jpg',
        'name': '레오',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 75,
        'image': process.env.PUBLIC_URL + 'img/Naiad.jpg',
        'name': '나이아스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 76,
        'image': process.env.PUBLIC_URL + 'img/Giltine.jpg',
        'name': '길티네',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 77,
        'image': process.env.PUBLIC_URL + 'img/Virupa.jpg',
        'name': '비루파',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'A',
        'amplifiTotal': 'S',
      },
      {
        'id': 78,
        'image': process.env.PUBLIC_URL + 'img/Willow Bachelor.jpg',
        'name': '버들도령',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'C',
        'amplifiTotal': 'C',
      },
      {
        'id': 79,
        'image': process.env.PUBLIC_URL + 'img/Ea.jpg',
        'name': '에아',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 80,
        'image': process.env.PUBLIC_URL + 'img/Raccoon.jpg',
        'name': '라쿤',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': '-',
        'normalRumble': 'S',
        'amplifiRumble': '-',
        'normalDuel': 'S',
        'amplifiDuel':'-',
        'normalRaid': 'B',
        'amplifiRaid': '-',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': '-',
        'normalTotal': 'S',
        'amplifiTotal': '-',
      },
      {
        'id': 81,
        'image': process.env.PUBLIC_URL + 'img/Pakhet.jpg',
        'name': '파크헤트',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'S',
        'normalRumble': 'S',
        'amplifiRumble': 'S',
        'normalDuel': 'S',
        'amplifiDuel':'S',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 82,
        'image': process.env.PUBLIC_URL + 'img/Bes.jpg',
        'name': '베스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 83,
        'image': process.env.PUBLIC_URL + 'img/Eshu.jpg',
        'name': '에슈',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'C',
        'amplifiTotal': 'C',
      },
      {
        'id': 84,
        'image': process.env.PUBLIC_URL + 'img/Ymir.jpg',
        'name': '이미르',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 85,
        'image': process.env.PUBLIC_URL + 'img/Maris.jpg',
        'name': '마르스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'C',
        'amplifiTotal': 'C',
      },
      {
        'id': 86,
        'image': process.env.PUBLIC_URL + 'img/Euros.jpg',
        'name': '귀여운 에우로스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'A',
        'normalDuel': 'A',
        'amplifiDuel':'S',
        'normalRaid': 'B',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'A',
      },
      {
        'id': 87,
        'image': process.env.PUBLIC_URL + 'img/Yuki Miku.jpg',
        'name': '유키미쿠',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 88,
        'image': process.env.PUBLIC_URL + 'img/Makoto.jpg',
        'name': '마코토',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 89,
        'image': process.env.PUBLIC_URL + 'img/Rusalka.jpg',
        'name': '루살카',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'A',
      },
      {
        'id': 90,
        'image': process.env.PUBLIC_URL + 'img/Rin.jpg',
        'name': '린',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'C',
        'amplifiTotal': 'C',
      },

      // 목속성 91~
      {
        'id': 91,
        'image': process.env.PUBLIC_URL + 'img/Summer Sitri.jpg',
        'name': '피터패트 시트리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'S',
        'amplifiRumble': 'S',
        'normalDuel': 'S',
        'amplifiDuel':'S',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 92,
        'image': process.env.PUBLIC_URL + 'img/Annie.jpg',
        'name': '애니',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'S',
        'amplifiRaid': 'S',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 93,
        'image': process.env.PUBLIC_URL + 'img/Guardian Deity Kouga.jpg',
        'name': '상아',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'S',
        'normalRumble': 'B',
        'amplifiRumble': 'S',
        'normalDuel': 'B',
        'amplifiDuel':'S',
        'normalRaid': 'B',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'S',
      },
      {
        'id': 94,
        'image': process.env.PUBLIC_URL + 'img/Hella.jpg',
        'name': '헬라',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 95,
        'image': process.env.PUBLIC_URL + 'img/Ayane.jpg',
        'name': '아야네',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 96,
        'image': process.env.PUBLIC_URL + 'img/Siren.jpg',
        'name': '세이렌',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 97,
        'image': process.env.PUBLIC_URL + 'img/Nicole.jpg',
        'name': '니콜',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 98,
        'image': process.env.PUBLIC_URL + 'img/Daphnis.jpg',
        'name': '다프니스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 99,
        'image': process.env.PUBLIC_URL + 'img/Lancer Ruin.jpg',
        'name': '꿰뚫는 루인',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 100,
        'image': process.env.PUBLIC_URL + 'img/Serval.jpg',
        'name': '서벌',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'C',
        'amplifiDungeon': 'C',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'C',
        'amplifiTotal': 'B',
      },
      {
        'id': 101,
        'image': process.env.PUBLIC_URL + 'img/Abaddon.jpg',
        'name': '아바돈',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 102,
        'image': process.env.PUBLIC_URL + 'img/Krampus.jpg',
        'name': '크람푸스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'A',
      },
]

export default childInfo;