const childInfo = [
    {
      'id': 1,
      'image': process.env.PUBLIC_URL + 'img/브리지드.JPG',
      'name': '브리지드',
      'normalSkill': '일반스킬',
      'amplifiSkill': '증폭스킬',
      'normalDungeon': 'A',
      'amplifiDungeon': 'S',
      'normalRumble': 'A',
      'amplifiRumble': 'S',
      'normalDuel': 'A',
      'amplifiDuel':'S',
      'normalRaid': 'B',
      'amplifiRaid': 'A',
      'normalWorldBoss': 'B',
      'amplifiWorldBoss': 'A',
      'normalTotal': 'A',
      'amplifiTotal': 'S',
    },
    {
      'id': 2,
      'image': process.env.PUBLIC_URL + 'img/고검 티아마트.JPG',
      'name': '고검 티아마트',
      'normalSkill': '일반스킬',
      'amplifiSkill': '증폭스킬',
      'normalDungeon': 'A',
      'amplifiDungeon': 'A',
      'normalRumble': 'C',
      'amplifiRumble': 'C',
      'normalDuel': 'C',
      'amplifiDuel':'C',
      'normalRaid': 'S',
      'amplifiRaid': 'S',
      'normalWorldBoss': 'B',
      'amplifiWorldBoss': 'B',
      'normalTotal': 'A',
      'amplifiTotal': 'A',
    },
    {
        'id': 3,
        'image': process.env.PUBLIC_URL + 'img/모건.JPG',
        'name': '모건',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 4,
        'image': process.env.PUBLIC_URL + 'img/러블리 레다.JPG',
        'name': '러블리 레다',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 5,
        'image': process.env.PUBLIC_URL + 'img/베리드 다비.JPG',
        'name': '베리드 다비',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'A+',
        'amplifiRaid': 'A+',
        'normalWorldBoss': 'S',
        'amplifiWorldBoss': 'S',
        'normalTotal': 'S',
        'amplifiTotal': 'S',
      },
      {
        'id': 6,
        'image': process.env.PUBLIC_URL + 'img/매혹 바토리.JPG',
        'name': '매혹 바토리',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 7,
        'image': process.env.PUBLIC_URL + 'img/카인.JPG',
        'name': '카인',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 8,
        'image': process.env.PUBLIC_URL + 'img/티르빙.JPG',
        'name': '티르빙',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 9,
        'image': process.env.PUBLIC_URL + 'img/메브.JPG',
        'name': '메브',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 10,
        'image': process.env.PUBLIC_URL + 'img/살라딘.JPG',
        'name': '살라딘',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 11,
        'image': process.env.PUBLIC_URL + 'img/지바.JPG',
        'name': '지바',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 11,
        'image': process.env.PUBLIC_URL + 'img/코우카.JPG',
        'name': '코우카',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'B',
        'amplifiRaid': 'B',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 12,
        'image': process.env.PUBLIC_URL + 'img/헤스티아.JPG',
        'name': '헤스티아',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'A',
        'normalRumble': 'C',
        'amplifiRumble': 'B',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'A',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'C',
        'amplifiTotal': 'A',
      },
      {
        'id': 13,
        'image': process.env.PUBLIC_URL + 'img/구미호.JPG',
        'name': '구미호',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'A',
        'amplifiRumble': 'S',
        'normalDuel': 'A',
        'amplifiDuel':'A+',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B',
        'amplifiWorldBoss': 'B',
        'normalTotal': 'A',
        'amplifiTotal': 'S',
      },
      {
        'id': 14,
        'image': process.env.PUBLIC_URL + 'img/리모스.JPG',
        'name': '리모스',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'S',
        'normalDuel': 'A',
        'amplifiDuel':'A',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'S',
      },
      {
        'id': 15,
        'image': process.env.PUBLIC_URL + 'img/알릴.JPG',
        'name': '알릴',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'A',
        'amplifiRumble': 'A',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'C',
        'amplifiWorldBoss': 'C',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
      {
        'id': 16,
        'image': process.env.PUBLIC_URL + 'img/레이팡.JPG',
        'name': '레이팡',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'B',
        'amplifiDungeon': 'B',
        'normalRumble': 'C',
        'amplifiRumble': 'C',
        'normalDuel': 'C',
        'amplifiDuel':'C',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'A',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'B',
        'amplifiTotal': 'B',
      },
      {
        'id': 17,
        'image': process.env.PUBLIC_URL + 'img/스쿨라이프 이브.JPG',
        'name': '스쿨라이프 이브',
        'normalSkill': '일반스킬',
        'amplifiSkill': '증폭스킬',
        'normalDungeon': 'A',
        'amplifiDungeon': 'A',
        'normalRumble': 'B',
        'amplifiRumble': 'B',
        'normalDuel': 'B',
        'amplifiDuel':'B',
        'normalRaid': 'C',
        'amplifiRaid': 'C',
        'normalWorldBoss': 'B+',
        'amplifiWorldBoss': 'A',
        'normalTotal': 'A',
        'amplifiTotal': 'A',
      },
]

export default childInfo;